import Hero from "@/components/shared/Hero";
import Navbar from "@/components/shared/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black text-white`}
      >
        <Navbar />
        <Hero />
        <div className="container mx-auto px-4 py-8">
          {children}
        </div>

      </body>
    </html>
  );
}
